### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Addressing the alerts flagged in https://github.com/microsoft/angular2-slickgrid/network/alerts

While these are unlikely to result in actual issues in the application (most of these are dev dependencies) the updates are minor and keeping up with the latest versions of packages is good maintenance.

### CODE REVIEW

**Comment by anthonydresser** [comment]
We need to be careful here, I don't agree we should always keep up to date on dependencies since updated dependencies can have breaking or behavior changes.

I already see a problem here, gulp-typescript wants a typescript version of >= 2.7.1 and we are using 2.3

**Comment by Charles-Gagnon** [comment]
Hm, good catch. Odd though since I was able to build it just fine. I'll investigate and see if there's any issue here.

**Comment by Charles-Gagnon** [comment]
@anthonydresser Where are you seeing that it wants typescript >= 2.7.1?

**Comment by anthonydresser** [comment]
https://github.com/ivogabe/gulp-typescript/blob/d0410c2dc37cd4259689e4bc354a8ec68e779823/package.json#L91

**Comment by Charles-Gagnon** [comment]
I updated typescript to the latest 2.x and tested it out locally, things seem to be fine. Any issues you can think of with that? I was considering updating to the version ADS uses too (3.4.5) - think that's worth the effort?

**Pull request closed without merging**
